### ISSUE TITLE
Order clusters in recon and not in plotting

### ISSUE THREAD

**Issue by csgro** [lucabaldini/xperecon#4]
This would make direct plotting with root file easier

**Comment by gspandre** [comment]
If you have not yet done I can do it (but next week when I come back at work)

Inviato da iPhone

**Comment by csgro** [comment]
TMainGui.cxx modified with the addition of:

bool sort_by_ph (TCluster\* x, TCluster\* y) { return (x->fPulseHeight > y->fPulseHeight); }

and 

sort(Polarimeter->fAllClusts, Polarimeter->fAllClusts + NbClusters, sort_by_ph);

in TMainGUI::SaveClusters
It seems to work so we can close this issue
